name: planner
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.2.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_iconly: ^1.0.2
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_sign_in: ^6.1.6
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  foundation: ^0.0.5
  go_router: ^13.1.0
  cloud_firestore: ^4.15.3
  uuid: ^4.3.3
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

